### ISSUE TITLE
Site fails to render

### ISSUE THREAD

**Issue by mneil** [sethmacleod/dimension#21]
Just starting out with Hugo playing around. 

Windows, latest version of Hugo
Added dimension as a submodule
Ran `hugo server -D`

The console shows:
```
 Error while rendering "home": template: theme/index.html:18:44: executing "theme/index.html" at <safeHTML>: wrong number of args for safeHTML: want 1 got 0
```

Lines 18-19 reference Site.Params.{prop} with both properties in lowercase. Looking at other templates Site.Params is not necessary and the prop is Pascal case. I changed title to Title and description to Description and the site renders.

**Comment by sethmacleod** [comment]
Hi @mneil 

Strange, because I'm not replicating this error. I am using Windows 10 & Hugo v0.27.1. These are the steps I took:

1. `hugo new site test`
2. `cd test`
3. `git init`
4. `git submodule add https://github.com/sethmacleod/dimension.git themes/dimension`
5. Copy contents of `\test\themes\dimension\exampleSite` to `\test`
6. `hugo server -D`

I am not getting any errors. I do get a warning regarding `disableRSS` being deprecated, which I will have to deal with.

Regarding `.Site.Params`, Hugo has changed a lot since I last used it, and I cannot remember if this was how it had to be when I first set this up. According to the [current docs](https://gohugo.io/variables/site/#the-site-params-variable), it should be `.Site.Title` and `.Site.Params.description`. I have tested this and that works. `.Site.Description` does not work.

**Comment by mneil** [comment]
Thank you for getting back to me. Ok, this makes sense. I installed some other themes and they "worked" without having to take any additional steps other than setting the theme to the correct folder name. In my haste I failed to read through the entire README before opening a ticket. I can see now that you require, at least to get started, copying the config and some of the content from the example site to produce the output from the demo. I am closing this out. Thanks again!
